name: Linter

on:
  - push
  - pull_request

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Ruff
        uses: chartboost/ruff-action@v1
        with:
          args: 'format --check'
